tests:
  restart: "no"
  build: .
  links:
    - graphite
    - redis
  volumes:
    - .:/code
  command: "true"

authentication:
  restart: "no"
  build: .
  ports:
    - "8000:8000"
  command: /usr/local/bin/gunicorn auth:api --reload --log-level debug -w 8 -b :8000
  links:
    - graphite
    - redis
  volumes:
    - .:/code

home:
  restart: "no"
  build: .
  ports:
    - "8001:8001"
  command: /usr/local/bin/gunicorn homepage:api --reload --log-level debug -w 8 -b :8001
  links:
    - authentication
    - recommendations
    - popular
    - graphite
    - redis
  volumes:
    - .:/code

recommendations:
  restart: "no"
  build: .
  ports:
    - "8002:8002"
  command: /usr/local/bin/gunicorn recommendations:api --reload --log-level debug --capture-output -w 8 -b :8002
  links:
    - authentication
    - graphite
    - redis
  volumes:
    - .:/code

popular:
  restart: "no"
  build: .
  ports:
    - "8003:8003"
  command: /usr/local/bin/gunicorn popular_items:api --reload --log-level debug -w 8 -b :8003
  links:
    - authentication
    - graphite
    - redis
  volumes:
    - .:/code

nginx:
  restart: "no"
  build: ./nginx/
  ports:
    - "80:80"
  links:
    - home
  volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d

graphite:
  restart: "no"
  build: ./graphite/
  ports:
    - "81:80"
    - "2003:2003"
    - "2004:2004"
    - "2023:2023"
    - "2024:2024"
    - "8127:8126"
    - "8125:8125/udp"

redis:
  restart: "no"
  image: redis
  ports:
    - "6379"
