tests:
  restart: "no"
  build: .
  links:
    - test-redis:redis
  volumes:
    - .:/code
  command: ["py.test"]

authentication:
  restart: "no"
  build: .
  ports:
    - "8000:8000"
  command: /usr/local/bin/gunicorn auth:api --reload --log-level debug -w 8 -b :8000
  links:
    - redis
  volumes:
    - .:/code

home:
  restart: "no"
  build: .
  ports:
    - "8001:8001"
  command: /usr/local/bin/gunicorn homepage:api --reload --log-level debug -w 8 -b :8001
  links:
    - authentication
    - recommendations
    - popular
    - redis
  volumes:
    - .:/code

recommendations:
  restart: "no"
  build: .
  ports:
    - "8002:8002"
  command: /usr/local/bin/gunicorn recommendations:api --reload --log-level debug --capture-output -w 8 -b :8002
  links:
    - authentication
    - redis
  volumes:
    - .:/code

popular:
  restart: "no"
  build: .
  ports:
    - "8003:8003"
  command: /usr/local/bin/gunicorn popular_items:api --reload --log-level debug -w 8 -b :8003
  links:
    - authentication
    - redis
  volumes:
    - .:/code

settings:
  restart: "no"
  build: .
  ports:
    - "8004:8004"
  command: /usr/local/bin/gunicorn settings:api --reload --log-level debug -w 8 -b :8004
  links:
    - redis
  volumes:
    - .:/code

metrics:
  restart: "no"
  build: .
  ports:
    - "8005:8005"
  command: /usr/local/bin/gunicorn metrics:api --reload --log-level debug -w 8 -b :8005
  links:
    - redis
  volumes:
    - .:/code

nginx:
  restart: "no"
  build: ./nginx/
  ports:
    - "80:80"
  links:
    - home
  volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d

redis:
  restart: "no"
  image: redis
  ports:
    - "6379"

test-redis:
  restart: "no"
  image: redis
  ports:
    - "6378:6379"
