authentication:
  restart: always
  build: .
  ports:
    - "8000:8000"
  command: /usr/local/bin/gunicorn auth:api -w 2 -b :8000
  links:
    - graphite

home:
  restart: always
  build: .
  ports:
    - "8001:8001"
  command: /usr/local/bin/gunicorn homepage:api -w 2 -b :8001
  links:
    - authentication
    - recommendations
    - graphite

recommendations:
  restart: always
  build: .
  ports:
    - "8002:8002"
  command: /usr/local/bin/gunicorn recommendations:api -w 2 -b :8002
  links:
    - authentication
    - graphite

popular:
  restart: always
  build: .
  ports:
    - "8003:8003"
  command: /usr/local/bin/gunicorn popular:api -w 2 -b :8003
  links:
    - authentication
    - graphite

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  links:
    - home
  volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d

graphite:
  restart: always
  build: ./graphite/
  ports:
    - "81:80"
    - "2003:2003"
    - "2004:2004"
    - "2023:2023"
    - "2024:2024"
    - "8127:8126"
    - "8125:8125/udp"
